name: Unit Tests

on: workflow_call

jobs:
  test:
    name: Test on ${{matrix.python.toxenv}}-${{matrix.platform.toxenv}}
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            toxenv: linux
          - runner: windows-latest
            toxenv: windows
        python:
          - version: '3.10'
            toxenv: 'py310'
          - version: '3.11'
            toxenv: 'py311'
    steps:
      - uses: actions/checkout@v3
      - name: Install Python ${{ matrix.python.version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python.version }}
          cache: 'pip' # cache pip dependencies
      - uses: ilammy/msvc-dev-cmd@v1
        if: matrix.platform.toxenv == 'windows'
      - name: Install tox
        run: python -m pip install tox
      - name: Install signal-temporal-logic
        run: |
          git clone -b v0.1.3-post1+py311 https://github.com/davidhjp01/signal-temporal-logic build/stl
          pip install -U build/stl/
      - name: Run pytest
        run: tox -e ${{matrix.python.toxenv}}-${{matrix.platform.toxenv}}
